const INITIAL_DATA = [
  {
    id: '1',
    titel: 'Bluse',
    color: 'grau',
    pattern: 'floral',
    material: 'Leinen',
    fitting: 'Lose Fit',
    imageUrl: '/images/bluse-floral.png',
  },
  {
    id: '2',
    titel: 'Pullover',
    color: 'grün',
    pattern: 'einfarbig',
    material: 'Wolle',
    fitting: 'Lose Fit',
    imageUrl: '/images/pullover-gruen.png',
  },
  {
    id: '3',
    titel: 'Pullover',
    color: 'pink',
    pattern: 'einfarbig',
    material: 'Baumwolle',
    fitting: 'Regular Fit',
    imageUrl: '/images/pullover-rosa.png',
  },
  {
    id: '4',
    titel: 'T-Shirt',
    color: 'weiß',
    pattern: 'floral',
    material: 'Baumwolle',
    fitting: 'Figurbetont',
    imageUrl: '/images/t-shirt-floral.png',
  },
  {
    id: '5',
    titel: 'Bluse',
    color: 'grau',
    pattern: 'floral',
    material: 'Leinen',
    fitting: 'Lose Fit',
    imageUrl: '/images/bluse-floral.png',
  },
  {
    id: '6',
    titel: 'Pullover',
    color: 'grün',
    pattern: 'einfarbig',
    material: 'Wolle',
    fitting: 'Lose Fit',
    imageUrl: '/images/pullover-gruen.png',
  },
  {
    id: '7',
    titel: 'Pullover',
    color: 'pink',
    pattern: 'einfarbig',
    material: 'Baumwolle',
    fitting: 'Regular Fit',
    imageUrl: '/images/pullover-rosa.png',
  },
  {
    id: '8',
    titel: 'T-Shirt',
    color: 'weiß',
    pattern: 'floral',
    material: 'Baumwolle',
    fitting: 'Figurbetont',
    imageUrl: '/images/t-shirt-floral.png',
  },
]

export default INITIAL_DATA
