const INITIAL_DATA = [
  {
    id: 1,
    category: 'Bluse',
    title: 'Bluse',
    color: 'grau',
    pattern: 'floral',
    material: 'Leinen',
    fitting: 'Lose Fit',
    imageUrl: '/images/bluse-floral.png',
    isBookmarked: false,
  },
  {
    id: 2,
    category: 'Pullover',
    title: 'Pullover',
    color: 'grün',
    pattern: 'einfarbig',
    material: 'Wolle',
    fitting: 'Lose Fit',
    imageUrl: '/images/pullover-gruen.png',
    isBookmarked: false,
  },
  {
    id: 3,
    category: 'Pullover',
    title: 'Pullover',
    color: 'pink',
    pattern: 'einfarbig',
    material: 'Baumwolle',
    fitting: 'Regular Fit',
    imageUrl: '/images/pullover-rosa.png',
    isBookmarked: false,
  },
  {
    id: 4,
    category: 'T-Shirt',
    title: 'T-Shirt',
    color: 'weiß',
    pattern: 'floral',
    material: 'Baumwolle',
    fitting: 'Figurbetont',
    imageUrl: '/images/t-shirt-floral.png',
    isBookmarked: false,
  },
  {
    id: 5,
    category: 'Hose',
    title: 'Jeans Hose',
    color: 'blau',
    pattern: 'einfarbig',
    material: 'Jeansstoff',
    fitting: 'Figurbetont',
    imageUrl: '/images/IMG_1273.JPG',
    isBookmarked: false,
  },
  {
    id: 6,
    category: 'Jumpsuit',
    title: 'Jumpsuit',
    color: 'bunt',
    pattern: 'floral',
    material: 'Seide',
    fitting: 'Lose Fit',
    imageUrl: '/images/IMG_1278.JPG',
    isBookmarked: false,
  },
  {
    id: 7,
    category: 'Pullover',
    title: 'Special Pullover',
    color: 'schwarz',
    pattern: 'einfarbig',
    material: 'Baumwolle',
    fitting: 'Regular Fit',
    imageUrl: '/images/IMG_1283.JPG',
    isBookmarked: false,
  },
  {
    id: 8,
    category: 'Strickjacke',
    title: 'Strickjacke',
    color: 'blau',
    pattern: 'einfarbig',
    material: 'Baumwolle',
    fitting: 'Lose Fit',
    imageUrl: '/images/IMG_1279.JPG',
    isBookmarked: false,
  },
]

export default INITIAL_DATA
